#!/bin/bash
#############################################################################
# Program : Make My Code
# Author : Chauncey Yan
# Description : Make the sample code for different code(C,Bash,Perl)
# Revision : 0.2
# Date : May 22st
# Update : Added function to distinguish the path and file name
# Known issue : 
#############################################################################
# Initialization :
#############################################################################
filepath=$1
# stripped the function to distinguish the path and file name for no reason
slash=`echo $1 | grep "/"` 
if [[ -n $slash ]];then
	filename=`echo $1 | awk -F'/' '{print $NF}'`
	filedir=`echo $1 | awk -F'/' '{for (i=0;i<NF;i++) print $i }'`
	echo fn:$filename fd:$filedir fp:$filepath
fi

#############################################################################
# Function : 
#############################################################################
function longline(){
  	for i in `seq 1 $1`; do
		echo -n "$commentc" >> $filepath
	done
}

#############################################################################
# Main
#############################################################################

if [[ -n $filepath ]];then
	if [[ -e $filepath ]];then
		echo $filepath exists. Overwrite it? y/n
		read input
		if [ $input != 'y' ] && [ $input != "yes" ];then
			exit
		fi
	fi
	if [[ $2 == 'b' ]];then
		shebang="#!/bin/bashi\n"
		commenta='#'
		commentb='#'
		commentc='#'
	elif [[ $2 == 'p' ]];then
		shebang="#!/wv/pevtools/aoi/bin/perl\n"
		commenta='#'
		commentb='#'
		commentc='#'
	elif [[ $2 == 'c' ]];then
		commenta="//"
		commentb="/*"
		commentc="*"
		commentd="*/"
	else
		echo Supported arguments:
		echo "mkmyco -c(C/C++) -b(Bash) -p(Perl)"
		exit
	fi
	# Make a new file
	echo -n -e $shebang > $filepath
	echo -n "$commentb" >> $filepath
	longline 100
	echo >> $filepath
	echo -e "$commentc" Program'\t': >> $filepath
	echo -e "$commentc" Author'\t': Chauncey Yan >> $filepath
	echo -e "$commentc" Functions'\t': >> $filepath
	echo -e "$commentc" Revison'\t': 0.1 >> $filepath
	echo -e "$commentc" Mod date'\t': May 22st >> $filepath
	echo -e "$commentc" Updates'\t':  >> $filepath
	echo -e "$commentc" Issues'\t':  >> $filepath
	longline 100
	echo "$commentd" >> $filepath
else
	echo Please provide a name for the file and an file type.
	echo "EXAMPLE: mkmyco -c(C/C++) -b(Bash) -p(Perl)"
	exit
fi
# Check if there is a shebang and chmod to excutable accordingly
if [[ -n $shebang ]];then
	chmod 755 $filepath
fi



